@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":PinCommandParser" as PinCommandParser LOGIC_COLOR
participant "c:PinCommand" as PinCommand LOGIC_COLOR
participant "<<utility>>\nCommandUtil" as CommandUtil LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> AddressBookParser : parseCommand("pin n/David Ng p/90002222")
activate AddressBookParser

AddressBookParser -> PinCommandParser : parse(arguments)
activate PinCommandParser

create PinCommand
PinCommandParser -> PinCommand
activate PinCommand
PinCommand --> PinCommandParser : c
deactivate PinCommand

PinCommandParser --> AddressBookParser : c
deactivate PinCommandParser
destroy PinCommandParser

[<-- AddressBookParser : c
deactivate AddressBookParser

[-> PinCommand : execute(model)
activate PinCommand

PinCommand -> Model : findPersons(targetInfo)
activate Model
Model --> PinCommand : matches
deactivate Model

note right of PinCommand
    Filter matches to unpinnedMatches
    using model.isPersonPinned(person)
end note

alt no contacts match
    [<-- PinCommand : throw CommandException (No match)

else all matching contacts are already pinned
    [<-- PinCommand : throw CommandException (Already pinned)

else at least one unpinned match found
    PinCommand -> CommandUtil : targetPersonFromMatches(model, unpinnedMatches)
    activate CommandUtil
    CommandUtil --> PinCommand : personToPin
    deactivate CommandUtil

    PinCommand -> Model : pinPerson(personToPin)
    activate Model
    Model --> PinCommand
    deactivate Model

    PinCommand -> Model : showAllPersonsPinnedFirst()
    activate Model
    Model --> PinCommand
    deactivate Model

    PinCommand -> Model : showNoEvents()
    activate Model
    Model --> PinCommand
    deactivate Model

    [<-- PinCommand : result
end

deactivate PinCommand
PinCommand -[hidden]-> PinCommand
destroy PinCommand
@enduml
